chore(go.mod): bump grafana/pyroscope-go deps (#3849)
On Go 1.23 I got such failures:

```
% make build
--> Updating go.mod
--> Updating go.mod in ./test/interchain
# github.com/grafana/pyroscope-go/godeltaprof/internal/pprof
../../../go/pkg/mod/github.com/grafana/pyroscope-go/godeltaprof@v0.1.6/internal/pprof/delta_mutex.go:30:20: undefined: runtime_cyclesPerSecond
../../../go/pkg/mod/github.com/grafana/pyroscope-go/godeltaprof@v0.1.6/internal/pprof/proto.go:320:8: undefined: runtime_expandFinalInlineFrame
make: *** [build] Error 1
```

Due to recent change in Go 1.23 where Go team removed some internal
things. Simple bump works fine.

(cherry picked from commit 2c74ea5c79345fdc03c74c7389d26f2bf579c578)

# Conflicts:
#	go.mod
#	go.sum