feat: override timeout commit via `--timeout-commit` (#4103)
Closes https://github.com/celestiaorg/celestia-app/issues/4080

## Testing

1. `./scripts/single-node.sh` now makes blocks faster 🎊
2. `./scripts/arabica.sh` throws an error if you try to add
`--timeout-commit 1s`

```
Error: the --timeout-commit flag was used on arabica-11 but it is unsupported on public networks: arabica-11, mocha-4, celestia. The --timeout-commit flag should only be used on private testnets.
```

(cherry picked from commit d20916c7b97b870ff1a2e358e2403b9715d403b1)

# Conflicts:
#	cmd/celestia-appd/cmd/start.go
#	scripts/single-node.sh