this Docker image does not have stride tx ica
```
Error Trace:	/Users/rootulp/git/rootulp/celestiaorg/celestia-app/interchaintest/ica_test.go:100
Error:      	Received unexpected error:
		exit code 1:  Error: unknown command "interchain-accounts" for "tx"
		Usage:
		  strided tx [flags]
		  strided tx [command]

		Available Commands:

		  bank                Bank transaction subcommands
		  broadcast           Broadcast transactions generated offline
		  claim               claim transactions subcommands
		  crisis              Crisis transactions subcommands
		  decode              Decode a binary encoded transaction string
		  distribution        Distribution transactions subcommands
		  encode              Encode transactions generated offline
		  evidence            Evidence transaction subcommands
		  feegrant            Feegrant transactions subcommands
		  gov                 Governance transactions subcommands
		  ibc                 IBC transaction subcommands
		  ibc-transfer        IBC fungible token transfer transaction subcommands
		  icacallbacks        icacallbacks transactions subcommands
		  multi-sign          Generate multisig signatures for transactions generated offline
		  records             records transactions subcommands
		  sign                Sign a transaction generated offline
		  sign-batch          Sign transaction batch files
		  slashing            Slashing transaction subcommands
		  stakeibc            stakeibc transactions subcommands
		  staking             Staking transaction subcommands
		  stridevesting       Stride vesting transaction subcommands
		  validate-signatures validate transactions signatures
		  vesting             Vesting transaction subcommands
		  vesting             Vesting transaction subcommands
```