fix: show bbr error message on `celestia-appd start` (#3851)
Closes https://github.com/celestiaorg/celestia-app/issues/3845

## Before

```
$ celestia-appd start
Error: exit status 1
```
## After

```
$ celestia-appd start

The BBR (Bottleneck Bandwidth and Round-trip propagation time) congestion control algorithm is not enabled in this system's kernel.
BBR is important for the performance of the p2p stack.

To enable BBR:
sudo modprobe tcp_bbr
net.core.default_qdisc=fq
net.ipv4.tcp_congestion_control=bbr
sudo sysctl -p

Then verify BBR is enabled:
sysctl net.ipv4.tcp_congestion_control

This node will get worse p2p performance using a different congestion control algorithm.
If you need to bypass this check use the --force-no-bbr flag.
Error: failed to execute 'sysctl net.ipv4.tcp_congestion_control' exit status 1
```