feat: implement gas price and gas limit customization for txsim (#4447)
<!--
Please read and fill out this form before submitting your PR.

Please make sure you have reviewed our contributors guide before
submitting your
first PR.
-->

## Overview

Resolves #4445

<!--
Please provide an explanation of the PR, including the appropriate
context,
background, goal, and rationale. If there is an issue with this
information,
please provide a tl;dr and link the issue.
-->

## Testing results

`txsim --key-path ~/.celestia-app --grpc-endpoint
validator-1.celestia-arabica-11.com:9090 --feegrant --blob 4
--blob-amounts 1 --blob-sizes 475000 --gas-limit 360000 --gas-price 1.0`

The fees were outrageous here - 16+ TIA. - [example
block](https://arabica.celenium.io/block/4973806?tab=transactions)

`txsim --key-path ~/.celestia-app --grpc-endpoint
validator-1.celestia-arabica-11.com:9090 --feegrant --blob 4
--blob-amounts 1 --blob-sizes 475000 --gas-limit 720000 --gas-price 0.5`

This fills 2MB with 8.25 TIA - [example
block](https://arabica.celenium.io/block/4973865?tab=transactions)

then using
`txsim --key-path ~/.celestia-app --grpc-endpoint
validator-1.celestia-arabica-11.com:9090 --feegrant --blob 4
--blob-amounts 1 --blob-sizes 475000 --gas-limit 3600000 --gas-price
0.1`

works and 2MB costs 1.65 TIA, much more reasonable - [example
block](https://arabica.celenium.io/block/4973906?tab=transactions)

### Failed testing

this also failed but idk why
```
txsim --key-path ~/.celestia-app --grpc-endpoint validator-1.celestia-arabica-11.com:9090 --feegrant --blob 4 --blob-amounts 1 --blob-sizes 475000 --gas-limit 18000000 --gas-price 0.02

Error: error funding accounts: broadcast tx error: insufficient minimum gas price for this node; got: 72000 required at least: 360000.000000000000000000: insufficient fee
```

going lower
```
txsim --key-path ~/.celestia-app --grpc-endpoint validator-1.celestia-arabica-11.com:9090 --feegrant --blob 4 --blob-amounts 1 --blob-sizes 475000 --gas-limit 12000000 --gas-price 0.03

Error: error funding accounts: broadcast tx error: insufficient minimum gas price for this node; got: 108000 required at least: 360000.000000000000000000: insufficient fee
```

and up a bit:
```
txsim --key-path ~/.celestia-app --grpc-endpoint validator-1.celestia-arabica-11.com:9090 --feegrant --blob 4 --blob-amounts 1 --blob-sizes 475000 --gas-limit 15000000 --gas-price 0.03

Error: error funding accounts: broadcast tx error: insufficient minimum gas price for this node; got: 108000 required at least: 360000.000000000000000000: insufficient fee
```

---------

Co-authored-by: Rootul P <rootulp@gmail.com>
(cherry picked from commit ba3a4481b7b3e232d2d90f94d60fda9fabd00ec0)

# Conflicts:
#	test/cmd/txsim/cli.go
#	test/txsim/run.go