docs: delete all contents of `~/.celestia-app`
I encountered an error:

```
$ celestia-appd tx payment payForData 0101010101010101 0101010101010101 --from validator --keyring-backend test
Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account celestia10etmzwghs0rcffu6dzs4wdw6wrumgcu2u3wl67 not found: key not found
```

because I failed to delete the `~/.celestia-app/keyring-test` from a previous devnet. After deleting it, I was able to successfully submit a PFD. This change updates the docs to suggest deleting the entire `~/.celestia-app` directory prior to running the single node script.